apiVersion: v1
kind: Service
metadata:
  name: ml-service
spec:
  type: LoadBalancer
  selector:
    app: ml-app
  ports:
    - port: 5000        # Expose service on 5000
      targetPort: 5000  # Forward to containerâ€™s Flask port
      protocol: TCP
